# Generated by Django 4.0.3 on 2022-04-11 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Underbanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('title', models.CharField(default='undefined', max_length=30)),
                ('description', models.TextField(default='description undefined', max_length=200)),
            ],
        ),
    ]
