# Generated by Django 4.0.3 on 2022-03-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='ciao', max_length=30)),
                ('localcode', models.IntegerField(default=3)),
                ('country', models.CharField(default='ciao', max_length=30)),
                ('region', models.CharField(default='ciao', max_length=30)),
            ],
        ),
    ]
