# Generated by Django 4.0.3 on 2022-03-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0002_underbanner'),
    ]

    operations = [
        migrations.AddField(
            model_name='underbanner',
            name='description',
            field=models.TextField(default='description undefined', max_length=200),
        ),
        migrations.AddField(
            model_name='underbanner',
            name='title',
            field=models.CharField(default='undefined', max_length=30),
        ),
    ]
