# Generated by Django 4.0.3 on 2022-03-29 15:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0003_underbanner_description_underbanner_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='homepage.airport')),
            ],
        ),
    ]
