# Generated by Django 4.0.3 on 2022-03-29 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0004_fly'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='arrive',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='arrive', to='homepage.airport'),
        ),
        migrations.AlterField(
            model_name='fly',
            name='start',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='start', to='homepage.airport'),
        ),
    ]
