# Generated by Django 4.0.3 on 2022-03-29 16:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0005_fly_arrive_alter_fly_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='orario',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 29, 16, 15, 35, 355243)),
        ),
    ]
