# Generated by Django 4.0.3 on 2022-03-30 14:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0007_alter_fly_orario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='orario',
            field=models.DateTimeField(default=datetime.datetime(2022, 3, 30, 14, 55, 42, 287807)),
        ),
    ]
