# Generated by Django 4.0.3 on 2022-04-11 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default='3c0b57af-e023-44b2-82ab-8f5813273db8', max_length=36)),
                ('name', models.CharField(max_length=250)),
                ('localcode', models.IntegerField()),
                ('country', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
            ],
        ),
    ]
