# Generated by Django 4.0.3 on 2022-04-20 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fly',
            name='fly_seats',
        ),
        migrations.AddField(
            model_name='fly',
            name='free_seats',
            field=models.IntegerField(blank=True, max_length=3, null=True),
        ),
    ]
