# Generated by Django 4.0.3 on 2022-04-21 14:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='date_rit',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
