# Generated by Django 4.0.3 on 2022-04-11 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(default='8310c802-f2f0-44b1-ae94-648b6b94ed5e', max_length=36)),
                ('model', models.CharField(max_length=100)),
                ('seats', models.IntegerField(default=60)),
                ('km_tot', models.IntegerField(default=0)),
                ('pilots_num', models.IntegerField(default=4)),
                ('team_num', models.IntegerField(default=4)),
            ],
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(default='7f7cd202-09d9-4361-b2c5-588f5c0939a6', max_length=36),
        ),
    ]
