# Generated by Django 4.0.3 on 2022-04-21 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_search_date_rit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='date_rit',
            field=models.DateField(blank=True, null=True),
        ),
    ]
