# Generated by Django 4.0.3 on 2022-04-11 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_aircraft_unique_id_alter_airport_unique_id_fly'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='unique_id',
            field=models.CharField(default='d15af5d3-6a23-4a33-8c26-9cb3a5289c5f', max_length=36),
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(default='baf2b5d9-26b2-4915-9a79-08db0b55e06b', max_length=36),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='fc22e57e-6428-4aed-8381-6c30ba796607', max_length=36),
        ),
    ]
