# Generated by Django 4.0.3 on 2022-04-20 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0003_alter_fly_free_seats'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('complete', 'complete'), ('pending', 'pending'), ('null', 'null')], default='null', max_length=15),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(blank=True, default='0', max_length=36),
        ),
    ]
