# Generated by Django 4.0.3 on 2022-04-21 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0004_alter_search_date_rit'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='have_return',
            field=models.BooleanField(default=False),
        ),
    ]
