# Generated by Django 4.0.3 on 2022-04-21 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0005_alter_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='ritorno',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unique_id',
            field=models.CharField(blank=True, default='0', max_length=36),
        ),
    ]
