# Generated by Django 4.0.3 on 2022-04-11 16:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0006_underbanner_alter_aircraft_unique_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=datetime.datetime.now)),
            ],
        ),
        migrations.DeleteModel(
            name='Underbanner',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='unique_id',
            field=models.CharField(default='2fbedda1-c2c9-47a9-8b56-091ca84df35d', max_length=36),
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(default='cf3a1f99-6219-4faf-a9bc-f9bb299aa999', max_length=36),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='790861a9-b383-423c-92db-c6d245b6f980', max_length=36),
        ),
        migrations.AddField(
            model_name='search',
            name='arrive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='S_arrive', to='booking.airport'),
        ),
        migrations.AddField(
            model_name='search',
            name='start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='S_start', to='booking.airport'),
        ),
    ]
