# Generated by Django 4.0.3 on 2022-04-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0007_alter_search_have_return'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='search',
            name='have_return',
        ),
        migrations.AddField(
            model_name='search',
            name='have_return2',
            field=models.CharField(blank=True, default='no', max_length=5, null=True),
        ),
    ]
