# Generated by Django 4.0.3 on 2022-04-11 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_alter_aircraft_unique_id_alter_airport_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='aircraft_seat',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='unique_id',
            field=models.CharField(default='47a7efb0-a0f4-41f8-a043-7fafaba6da95', max_length=36),
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(default='259dd77d-db2d-42b8-8532-7cc1c23f2b40', max_length=36),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='7d081b6c-be30-466d-b2ba-7b51d5e99e9c', max_length=36),
        ),
    ]
