# Generated by Django 4.0.3 on 2022-04-23 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0008_remove_search_have_return_search_have_return2'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='s1',
            field=models.CharField(default='n', max_length=100),
        ),
        migrations.AddField(
            model_name='search',
            name='s2',
            field=models.CharField(default='n', max_length=100),
        ),
    ]
