# Generated by Django 4.0.3 on 2022-04-23 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_search_s1_search_s2'),
    ]

    operations = [
        migrations.CreateModel(
            name='AeS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s1', models.CharField(max_length=100)),
                ('s2', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='search',
            name='s1',
        ),
        migrations.RemoveField(
            model_name='search',
            name='s2',
        ),
    ]
