# Generated by Django 4.0.3 on 2022-04-11 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0009_booking_aircraft_seat_alter_aircraft_unique_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='unique_id',
            field=models.CharField(default='255a63c5-0565-4ee6-8b96-3cb1ba430be3', max_length=36),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='unique_id',
            field=models.CharField(default='2ad22208-8e3b-4447-88ae-1ab1accd025b', max_length=36),
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(default='efb43f94-9321-4e42-9f40-c724a9204318', max_length=36),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='81863257-3d9d-4791-8331-7a335ed1ae12', max_length=36),
        ),
    ]
