# Generated by Django 4.0.3 on 2022-04-11 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0010_booking_unique_id_alter_aircraft_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='aircraft_seat',
        ),
        migrations.AddField(
            model_name='booking',
            name='airC_seat',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='unique_id',
            field=models.CharField(default='52e6d469-f115-45c3-aebf-af2b5db7d70a', max_length=36),
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(default='28aeefd3-1de8-42ec-a768-c5001cc8b6dd', max_length=36),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unique_id',
            field=models.CharField(default='7ab1b4bb-470c-4c59-91c5-5f91b9eca532', max_length=36),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='d50bd3d2-a37e-48b8-b771-2d10612cd87a', max_length=36),
        ),
    ]
