# Generated by Django 4.0.3 on 2022-04-23 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_alter_search_date_rit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='search',
            name='date_rit',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 23, 17, 45, 33, 560997), null=True),
        ),
    ]
