# Generated by Django 4.0.3 on 2022-04-11 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0011_remove_booking_aircraft_seat_booking_airc_seat_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='unique_id',
            field=models.CharField(default='e9249154-d000-4af8-8eae-2336cd408016', max_length=36),
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(default='3848d86a-0f23-456c-9aaf-07e25f43cb1b', max_length=36),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unique_id',
            field=models.CharField(default='8975a78a-e288-4139-8773-20d17ab8581e', max_length=36),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='b5a19744-a5df-4cbb-88d6-e181d9c26de8', max_length=36),
        ),
    ]
