# Generated by Django 4.0.3 on 2022-04-23 18:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_search_date_rit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aes',
            name='s1',
            field=models.CharField(default='nope', max_length=100),
        ),
        migrations.AlterField(
            model_name='aes',
            name='s2',
            field=models.CharField(default='nope', max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='date_rit',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 23, 18, 5, 43, 880826), null=True),
        ),
    ]
