# Generated by Django 4.0.3 on 2022-04-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0012_alter_aircraft_unique_id_alter_airport_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='unique_id',
            field=models.CharField(default='08ed8dac-b5e4-4c58-a4f2-ea56add315b9', max_length=36),
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(default='de3dae94-7849-4d25-9449-47d5275e22de', max_length=36),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unique_id',
            field=models.CharField(default='e2e11b54-de02-4b87-bb61-5b6726648118', max_length=36),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='da66236d-f7ea-4813-90fd-3728c442c3f8', max_length=36),
        ),
    ]
