# Generated by Django 4.0.3 on 2022-04-12 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0013_alter_aircraft_unique_id_alter_airport_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='unique_id',
            field=models.CharField(default='cceb488c-658f-4089-b0ea-b08408f3cd52', max_length=36),
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(default='06f931d5-d492-401c-af18-0d2853ce4198', max_length=36),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unique_id',
            field=models.CharField(default='326b816e-69f1-4e3b-9fbe-19bf11f491f8', max_length=36),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='6f4fc8e3-5da9-4494-8fc5-2bbced157d94', max_length=36),
        ),
    ]
