# Generated by Django 4.0.3 on 2022-04-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_aircraft_unique_id_alter_airport_unique_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='booking_code',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='unique_id',
            field=models.CharField(default='1a7fe5af-d3cb-4fc9-9da4-c59b161cc9f3', max_length=36),
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(default='4a543f6a-77a2-4a8e-89f2-132c11b0d4d0', max_length=36),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unique_id',
            field=models.CharField(default='3588cb73-7760-4d49-98df-f72fd9c9ae2b', max_length=36),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='f5e965f8-006a-4ebd-8bcd-9cda26bc60a2', max_length=36),
        ),
    ]
