# Generated by Django 4.0.3 on 2022-04-23 20:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0014_alter_search_date_rit'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aes',
            old_name='s2',
            new_name='sRitorno',
        ),
        migrations.AlterField(
            model_name='aes',
            name='s1',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='search',
            name='date_rit',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 23, 20, 32, 49, 560400), null=True),
        ),
    ]
