# Generated by Django 4.0.3 on 2022-04-15 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_remove_booking_booking_code_alter_aircraft_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='unique_id',
            field=models.CharField(default='ea30830b-1198-4750-ace3-76996327ad7b', max_length=36),
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(default='f873274f-acb3-4a21-9988-0963f689da06', max_length=36),
        ),
        migrations.AlterField(
            model_name='booking',
            name='airC_seat',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unique_id',
            field=models.CharField(default='6899d005-50c4-4904-b3f8-c75e990871cc', max_length=36),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='88a5ead1-e372-4cc7-ae9f-2304cddcfc78', max_length=36),
        ),
    ]
