# Generated by Django 4.0.3 on 2022-04-23 20:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0015_rename_s2_aes_sritorno_alter_aes_s1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aes',
            old_name='s1',
            new_name='sAndata',
        ),
        migrations.AlterField(
            model_name='search',
            name='date_rit',
            field=models.DateField(blank=True, default=datetime.datetime(2022, 4, 23, 20, 35, 41, 146327), null=True),
        ),
    ]
