# Generated by Django 4.0.3 on 2022-04-16 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0016_alter_aircraft_unique_id_alter_airport_unique_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Identification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=36)),
            ],
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='unique_id',
            field=models.CharField(default='1719aca4-de17-4f12-a649-ddcc093dd528', max_length=36),
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(default='b8bdc3d3-5d73-40f8-a326-0b2b9a072679', max_length=36),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unique_id',
            field=models.CharField(default='1e0fc1a7-e027-4458-9398-cf4281fb6275', max_length=36),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='af435b3a-c4cf-411f-b929-7d99009597b2', max_length=36),
        ),
    ]
