# Generated by Django 4.0.3 on 2022-04-16 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0017_identification_alter_aircraft_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='unique_id',
            field=models.CharField(default='a494ceda-79ca-42be-b995-3e61f8f0e868', max_length=36),
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(default='1c941df3-c32c-4ffd-b39a-3cfb474f8044', max_length=36),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unique_id',
            field=models.CharField(default='66629e9b-a546-4d47-bddc-529e4c85be60', max_length=36),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='d857aeed-fb82-4048-a059-76c2d8f0221c', max_length=36),
        ),
    ]
