# Generated by Django 4.0.3 on 2022-04-16 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0018_alter_aircraft_unique_id_alter_airport_unique_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aircraft',
            name='unique_id',
            field=models.CharField(default='3d6655f7-d8b1-4a07-b873-387f77ebcc94', max_length=36),
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(default='bbe4ab15-3e28-4495-83aa-4de17ca5368a', max_length=36),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unique_id',
            field=models.CharField(default='778c991f-f6e5-4d31-ab03-c9b160e01c76', max_length=36),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='4a87bc57-c154-433a-91d9-e1ffe5d1e04e', max_length=36),
        ),
    ]
