# Generated by Django 4.0.3 on 2022-04-16 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0019_alter_aircraft_unique_id_alter_airport_unique_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='identification',
            old_name='identification',
            new_name='saved_id',
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='unique_id',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='airport',
            name='unique_id',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='booking',
            name='unique_id',
            field=models.CharField(blank=True, max_length=36),
        ),
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(blank=True, max_length=36),
        ),
    ]
