# Generated by Django 4.0.4 on 2022-04-26 16:50

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=36)),
                ('model', models.CharField(max_length=100)),
                ('seats', models.IntegerField(default=60)),
                ('km_tot', models.IntegerField(default=0)),
                ('pilots_num', models.IntegerField(default=4)),
                ('team_num', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=36)),
                ('name', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('country', models.CharField(max_length=100)),
                ('region', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Identify',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(max_length=36)),
            ],
        ),
        migrations.CreateModel(
            name='People',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('people', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=36)),
                ('free_seats', models.IntegerField(default=10000)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('date_rit', models.DateField(blank=True, default=django.utils.timezone.now)),
                ('price', models.FloatField(default=50.0)),
                ('aircraft', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='starvato.aircraft')),
                ('arrive', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrive', to='starvato.airport')),
                ('start', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start', to='starvato.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_id', models.CharField(blank=True, max_length=36)),
                ('name', models.CharField(max_length=100)),
                ('surname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('fly_seat', models.CharField(max_length=4)),
                ('status', models.CharField(default='null', max_length=10)),
                ('fly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='starvato.fly')),
            ],
        ),
    ]
