# Generated by Django 4.0.3 on 2022-04-09 23:45

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_code', models.CharField(max_length=250, unique=True)),
                ('aircraft_model', models.CharField(max_length=250)),
                ('seats', models.IntegerField(default=40)),
                ('km_tot', models.IntegerField(blank=True, default=0, null=True)),
                ('pilots', models.IntegerField(default=4)),
                ('team', models.IntegerField(default=4)),
            ],
        ),
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('localcode', models.IntegerField()),
                ('country', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_code', models.CharField(blank=True, max_length=36, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('surname', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('address', models.CharField(max_length=200)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=200)),
                ('zip_code', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('hour', models.TimeField(default=datetime.datetime.now)),
                ('arrive', models.ForeignKey(default=-2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='arrive', to='prenotazione.airport')),
                ('start', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='start', to='prenotazione.airport')),
            ],
        ),
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fly_day', models.DateField(default=datetime.datetime.now)),
                ('Fly_hour', models.TimeField(default=datetime.datetime.now)),
                ('Fly_arrive', models.ForeignKey(default=-2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Fly_arrive', to='prenotazione.airport')),
                ('Fly_start', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Fly_start', to='prenotazione.airport')),
                ('aircraft', models.ForeignKey(default=-4, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft', to='prenotazione.aircraft')),
            ],
        ),
    ]
