# Generated by Django 4.0.3 on 2022-04-09 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='a', max_length=25),
        ),
    ]
