# Generated by Django 4.0.3 on 2022-04-12 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='unique_id',
            field=models.CharField(default='a3e918b4-5cfa-484b-bfeb-f5e37a76e6af', max_length=37),
        ),
    ]
