# Generated by Django 4.0.3 on 2022-04-04 15:30

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(default=datetime.datetime.now)),
                ('hour', models.TimeField(default=datetime.datetime.now)),
                ('arrive', models.ForeignKey(default=-2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='arrive', to='prenotazione.airport')),
                ('start', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='start', to='prenotazione.airport')),
            ],
        ),
    ]
