# Generated by Django 4.0.3 on 2022-04-04 17:00

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0002_search'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fly_day', models.DateField(default=datetime.datetime.now)),
                ('Fly_hour', models.TimeField(default=datetime.datetime.now)),
                ('Fly_arrive', models.ForeignKey(default=-2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Fly_arrive', to='prenotazione.airport')),
                ('Fly_start', models.ForeignKey(default=-1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Fly_start', to='prenotazione.airport')),
            ],
        ),
    ]
