# Generated by Django 4.0.3 on 2022-04-05 10:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0003_fly'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aircraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plate_code', models.CharField(max_length=250, unique=True)),
                ('aircraft_model', models.CharField(max_length=250)),
                ('seats', models.IntegerField(default=40)),
                ('km_tot', models.IntegerField(blank=True, default=django.db.models.deletion.SET_NULL, null=True)),
                ('pilots', models.IntegerField(default=4)),
                ('team', models.IntegerField(default=4)),
            ],
        ),
    ]
