# Generated by Django 4.0.3 on 2022-04-05 10:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0004_aircraft'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='aircraft',
            field=models.ForeignKey(default=-4, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aircraft', to='prenotazione.aircraft'),
        ),
        migrations.AlterField(
            model_name='aircraft',
            name='km_tot',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
