# Generated by Django 4.0.3 on 2022-03-31 10:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Airport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('localcode', models.IntegerField()),
                ('country', models.CharField(max_length=250)),
                ('region', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Fly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(null=True)),
                ('hourStart', models.TimeField()),
                ('arrive', models.ForeignKey(default=-2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrive', to='prenotazione.airport')),
                ('start', models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start', to='prenotazione.airport')),
            ],
        ),
    ]
