# Generated by Django 4.0.3 on 2022-04-04 14:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prenotazione', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='hourStart',
            field=models.TimeField(default=datetime.datetime.now),
        ),
        migrations.CreateModel(
            name='SearchFly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(null=True)),
                ('hourStart', models.TimeField(default=datetime.datetime.now)),
                ('arrive', models.ForeignKey(default=-2, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Search_arrive', to='prenotazione.airport')),
                ('start', models.ForeignKey(default=-1, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='Search_start', to='prenotazione.airport')),
            ],
        ),
    ]
