# Generated by Django 4.0.3 on 2022-04-24 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starvato_airlines', '0002_aircraft_fly'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='arrive',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arrive', to='starvato_airlines.airport'),
        ),
        migrations.AddField(
            model_name='fly',
            name='start',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='start', to='starvato_airlines.airport'),
        ),
    ]
