# Generated by Django 4.0.3 on 2022-04-24 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starvato_airlines', '0003_fly_arrive_fly_start'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='date',
            field=models.DateField(default=datetime.date(2022, 4, 24)),
        ),
    ]
