# Generated by Django 4.0.3 on 2022-04-24 10:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('starvato_airlines', '0004_fly_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='date',
            field=models.DateField(default=datetime.datetime(2022, 4, 24, 10, 7, 0, 316641, tzinfo=utc)),
        ),
    ]
