# Generated by Django 4.0.3 on 2022-04-24 10:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('starvato_airlines', '0005_alter_fly_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
