# Generated by Django 4.0.3 on 2022-04-24 10:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('starvato_airlines', '0006_alter_fly_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='hour',
            field=models.TimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='fly',
            name='price',
            field=models.FloatField(default=50.0),
        ),
    ]
