# Generated by Django 4.0.3 on 2022-04-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('starvato_airlines', '0008_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(default='null', max_length=10),
        ),
    ]
