# Generated by Django 4.0.4 on 2022-04-25 14:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('starvato_airlines', '0009_booking_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='fly',
            name='date_rit',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
