# Generated by Django 4.0.4 on 2022-04-25 14:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('starvato_airlines', '0010_fly_date_rit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fly',
            name='date_rit',
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
    ]
