# Generated by Django 4.0.4 on 2022-04-25 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('starvato_airlines', '0011_alter_fly_date_rit'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flyone', models.ForeignKey(blank=True, default=0, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='flyone', to='starvato_airlines.fly')),
                ('flytwo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flytwo', to='starvato_airlines.fly')),
            ],
        ),
    ]
